[package]
name    = "xtask"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow       = "1.0"
env_logger   = "0.9"
form         = "0.8"
log          = "0.4"
strum        = "0.24"
strum_macros = "0.24"
svd2rust     = "0.24"
svdtools     = "0.2"
toml         = "0.5"

[dependencies.clap]
version  = "3.1"
features = ["derive"]
