on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  check-riscv:
    name: Generate and build RISC-V PACs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [esp32c3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: riscv32imc-unknown-none-elf
          toolchain: nightly
          default: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path=xtask/Cargo.toml -- ${{ matrix.chip }}

  check-xtensa:
    name: Generate and build Xtensa PACs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chip: [esp32, esp32s2, esp32s3, esp8266]
    steps:
      - uses: actions/checkout@v2
      - uses: esp-rs/xtensa-toolchain@v1.2
        with:
          default: true
          ldproxy: false
          buildtargets: ${{ matrix.chip }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path=xtask/Cargo.toml -- ${{ matrix.chip }}
